export const STATUS_CODE = {
    SUCCESS: 'SUCCESS',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    BAD_REQUEST: 'BAD_REQUEST',
    CONFLICT: 'CONFLICT',
    USER_CREATED: 'USER_CREATED',
    UNAUTHORIZED: 'UNAUTHORIZED'
};